# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b54a26459e3ba25a2a324ca043699f4c941a2b24d61cf69ccc535a2c47be3a7a81089004388228a66bcf966da584f842b0053709f5cce71e412213f4d4bd9385

test:
  secret_key_base: 364a650864558d6e27b643eece1664f852ad1867a7127b04c5933fc0bfa00368d2b36eaf60e061ca5337fbd49edf7e7c5cafd5b451fa653f55cf33348c5acc40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
